apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-exporter
    k8s.kuboard.cn/name: go-exporter
  name: go-exporter
  namespace: kube-system
spec:
  clusterIP: 10.10.81.9
  ports:
    - name: go-exporter-metrics  #和sm文件一致
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    k8s.kuboard.cn/name: go-exporter
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: { }

